require:
  - rubocop-performance

AllCops:
  NewCops: enable

Layout/HashAlignment:
  EnforcedColonStyle: table

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - test/**/*

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
